import { moduleName } from './constants.js';

export function setConfig() {
  foundry.utils.setProperty(CONFIG, moduleName, {
    module: moduleName,
    automations: {
      legacy: {
        'Absorbing Tattoo, Acid': {
          name: 'Absorbing Tattoo, Acid',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Cold': {
          name: 'Absorbing Tattoo, Cold',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Fire': {
          name: 'Absorbing Tattoo, Fire',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Force': {
          name: 'Absorbing Tattoo, Force',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Lightning': {
          name: 'Absorbing Tattoo, Lightning',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Necrotic': {
          name: 'Absorbing Tattoo, Necrotic',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Poison': {
          name: 'Absorbing Tattoo, Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Psychic': {
          name: 'Absorbing Tattoo, Psychic',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Radiant': {
          name: 'Absorbing Tattoo, Radiant',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Thunder': {
          name: 'Absorbing Tattoo, Thunder',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        "Alchemist's Fire (flask)": {
          name: "Alchemist's Fire (flask)",
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin'],
        },
        'Arms of the Astral Self': {
          name: 'Arms of the Astral Self',
          type: 'Class Feature',
          version: '2.0.0',
          authors: ['Elwin', 'Spoob'],
        },
        'Arrow-Catching Shield': {
          name: 'Arrow-Catching Shield',
          type: 'Item',
          version: '4.0.2',
          authors: ['Elwin'],
        },
        'Channel Divinity: Rebuke the Violent': {
          name: 'Channel Divinity: Rebuke the Violent',
          type: 'Class Feature',
          version: '2.2.0',
          authors: ['Elwin'],
        },
        'Channel Divinity: Vow of Enmity': {
          name: 'Channel Divinity: Vow of Enmity',
          type: 'Class Feature',
          version: '3.1.0',
          authors: ['Elwin'],
        },
        'Clockwork Amulet': {
          name: 'Clockwork Amulet',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin', 'thatlonelybugbear'],
        },
        'Corpse Slayer Weapon': {
          name: 'Corpse Slayer Weapon',
          type: 'Item',
          version: '1.1.0',
          authors: ['Elwin', 'SagaTympana'],
        },
        'Crown of Stars': {
          name: 'Crown of Stars',
          type: 'Spell',
          version: '2.0.0',
          authors: ['Elwin', 'Bakana', 'Xenophes'],
        },
        'Dagger of Venom': {
          name: 'Dagger of Venom',
          type: 'Item',
          version: '2.0.2',
          authors: ['Elwin'],
        },
        'Dampen Elements': {
          name: 'Dampen Elements',
          type: 'Class Feature',
          version: '2.0.2',
          authors: ['Elwin'],
        },
        'Deflect Missiles': {
          name: 'Deflect Missiles',
          type: 'Class Feature',
          version: '2.1.1',
          authors: ['Elwin', 'Moto Moto', 'thatlonelybugbear'],
        },
        'Divine Allegiance': {
          name: 'Divine Allegiance',
          type: 'Class Feature',
          version: '4.0.2',
          authors: ['Elwin'],
        },
        'Drow Hand Crossbow': {
          name: 'Drow Hand Crossbow',
          type: 'Item',
          version: '1.1.0',
          authors: ['Elwin'],
        },
        'Drow Poison': {
          name: 'Drow Poison',
          type: 'Item',
          version: '2.0.2',
          authors: ['Elwin'],
        },
        'Fighting Style: Great Weapon Fighting': {
          name: 'Fighting Style: Great Weapon Fighting',
          type: 'Class Feature',
          version: '1.2.0',
          authors: ['Elwin', 'WurstKorn'],
        },
        'Flames of Phlegethos': {
          name: 'Flames of Phlegethos',
          type: 'Feat',
          version: '3.1.1',
          authors: ['Elwin'],
        },
        'Flame Tongue Greatsword': {
          name: 'Flame Tongue Greatsword',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin'],
        },
        'Flame Tongue Longsword': {
          name: 'Flame Tongue Longsword',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin'],
        },
        'Flame Tongue Rapier': {
          name: 'Flame Tongue Rapier',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Flame Tongue Scimitar': {
          name: 'Flame Tongue Scimitar',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin'],
        },
        'Flame Tongue Shortsword': {
          name: 'Flame Tongue Shortsword',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin'],
        },
        'Flash of Genius': {
          name: 'Flash of Genius',
          type: 'Class Feature',
          version: '2.1.0',
          authors: ['Elwin'],
        },
        'Gift of the Metallic Dragon': {
          name: 'Gift of the Metallic Dragon',
          type: 'Feat',
          version: '4.2.0',
          authors: ['Elwin'],
        },
        Goodberry: {
          name: 'Goodberry',
          type: 'Spell',
          version: '3.2.0',
          authors: ['Elwin'],
        },
        'Great Weapon Master': {
          name: 'Great Weapon Master',
          type: 'Feat',
          version: '3.0.3',
          authors: ['Elwin'],
        },
        'Guardian Emblem': {
          name: 'Guardian Emblem',
          type: 'Item',
          version: '4.2.0',
          authors: ['Elwin'],
        },
        'Moon-Touched Greatsword': {
          name: 'Moon-Touched Greatsword',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Moon-Touched Longsword': {
          name: 'Moon-Touched Longsword',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Moon-Touched Rapier': {
          name: 'Moon-Touched Rapier',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Moon-Touched Scimitar': {
          name: 'Moon-Touched Scimitar',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Moon-Touched Shortword': {
          name: 'Moon-Touched Shortword',
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Oathbow': {
          name: 'Oathbow',
          type: 'Item',
          version: '2.1.0',
          authors: ['Elwin', 'Christopher'],
        },
        'Poison, Basic (vial)': {
          name: 'Poison, Basic (vial)',
          type: 'Item',
          version: '2.0.2',
          authors: ['Elwin'],
        },
        Poisoner: {
          name: 'Poisoner',
          type: 'Class Features',
          version: '2.1.1',
          authors: ['Elwin'],
        },
        'Potent Poison': {
          name: 'Potent Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Psionic Power: Protective Field': {
          name: 'Psionic Power: Protective Field',
          type: 'Class Feature',
          version: '4.1.0',
          authors: ['Elwin'],
        },
        'Purple Worm Poison': {
          name: 'Purple Worm Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Recall Monster Lore': {
          name: 'Recall Monster Lore',
          type: 'Generic Action',
          version: '1.0.0',
          authors: ['Elwin','Fridan99'],
        },
        'Ring of Evasion': {
          name: 'Ring of Evasion',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        "Sentinel at Death's Door": {
          name: "Sentinel at Death's Door",
          type: 'Class Feature',
          version: '4.1.0',
          authors: ['Elwin'],
        },
        'Serpent Venom': {
          name: 'Serpent Venom',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        Sharpshooter: {
          name: 'Sharpshooter',
          type: 'Feat',
          version: '3.0.3',
          authors: ['Elwin'],
        },
        'Sorrowful Fate': {
          name: 'Sorrowful Fate',
          type: 'Class Feature',
          version: '2.2.0',
          authors: ['Elwin'],
        },
        'Spirit Shield': {
          name: 'Spirit Shield',
          type: 'Class Feature',
          version: '4.1.0',
          authors: ['Elwin'],
        },
        'Steady Aim': {
          name: 'Steady Aim',
          type: 'Class Feature',
          version: '3.1.0',
          authors: ['Elwin'],
        },
        'Sun Blade': {
          name: 'Sun Blade',
          type: 'Item',
          version: '2.2.0',
          authors: ['Elwin'],
        },
        "Tasha's Mind Whip": {
          name: "Tasha's Mind Whip",
          type: 'Spell',
          version: '2.0.0',
          authors: ['Elwin', 'Moto Moto'],
        },
        'Unwavering Mark': {
          name: 'Unwavering Mark',
          type: 'Class Feature',
          version: '3.2.0',
          authors: ['Elwin'],
        },
        'Vengeful Ancestors': {
          name: 'Vengeful Ancestors',
          type: 'Class Feature',
          version: '3.1.0',
          authors: ['Elwin'],
        },
        'Vigilant Guardian': {
          name: 'Vigilant Guardian',
          type: 'Race Feature',
          version: '4.0.2',
          authors: ['Elwin'],
        },
        'Warding Flare': {
          name: 'Warding Flare',
          type: 'Class Feature',
          version: '3.2.0',
          authors: ['Elwin'],
        },
        'Warding Maneuver': {
          name: 'Warding Maneuver',
          type: 'Class Feature',
          version: '2.1.1',
          authors: ['Elwin'],
        },
        'Wyvern Poison': {
          name: 'Wyvern Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
      },
      modern: {
        "Alchemist's Fire": {
          name: "Alchemist's Fire",
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Arrow-Catching Shield': {
          name: 'Arrow-Catching Shield',
          type: 'Item',
          version: '1.0.2',
          authors: ['Elwin'],
        },
        'Clockwork Amulet': {
          name: 'Clockwork Amulet',
          type: 'Item',
          version: '1.0.1',
          authors: ['Elwin', 'thatlonelybugbear'],
        },
        'Dagger of Venom': {
          name: 'Dagger of Venom',
          type: 'Item',
          version: '1.0.1',
          authors: ['Elwin'],
        },
        'Deflect Attacks': {
          name: 'Deflect Attacks',
          type: 'Class Feature',
          version: '1.1.1',
          authors: ['Elwin'],
        },
        'Flame Tongue': {
          name: 'Flame Tongue',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        Goodberry: {
          name: 'Goodberry',
          type: 'Spell',
          version: '1.1.0',
          authors: ['Elwin'],
        },
        'Great Weapon Fighting': {
          name: 'Great Weapon Fighting',
          type: 'Feat',
          version: '1.2.0',
          authors: ['Elwin', 'WurstKorn'],
        },
        'Great Weapon Master': {
          name: 'Great Weapon Master',
          type: 'Feat',
          version: '1.0.1',
          authors: ['Elwin'],
        },
        'Improved Warding Flare': {
          name: 'Improved Warding Flare',
          type: 'Class Feature',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        "Lolth's Sting": {
          name: "Lolth's Sting",
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Oathbow': {
          name: 'Oathbow',
          type: 'Item',
          version: '2.1.0',
          authors: ['Elwin', 'Christopher'],
        },
        'Poison, Basic': {
          name: 'Poison, Basic',
          type: 'Item',
          version: '1.0.1',
          authors: ['Elwin'],
        },
        Poisoner: {
          name: 'Poisoner',
          type: 'Feat',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Potent Poison': {
          name: 'Potent Poison',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Purple Worm Poison': {
          name: 'Purple Worm Poison',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Ring of Evasion': {
          name: 'Ring of Evasion',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Serpent Venom': {
          name: 'Serpent Venom',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Sharpshooter': {
          name: 'Sharpshooter',
          type: 'Feat',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Steady Aim': {
          name: 'Steady Aim',
          type: 'Class Feature',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Sun Blade': {
          name: 'Sun Blade',
          type: 'Item',
          version: '1.1.0',
          authors: ['Elwin'],
        },
        'Warding Flare': {
          name: 'Warding Flare',
          type: 'Class Feature',
          version: '3.2.0',
          authors: ['Elwin'],
        },
        'Wyvern Poison': {
          name: 'Wyvern Poison',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
      },
    },
    monsterAutomations: {
      legacy: {
        'Goblin Psi Commander': {
          'Psionic Shield': {
            name: 'Psionic Shield',
            version: '2.1.1',
            authors: ['Elwin'],
          },
        },
        Lich: {
          'Negative Energy Tether': {
            name: 'Negative Energy Tether',
            version: '2.0.2',
            authors: ['Elwin'],
          },
        },
        Medusa: {
          'Petrifying Gaze': {
            name: 'Petrifying Gaze',
            version: '1.1.0',
            authors: ['Elwin', 'Moto Moto'],
          },
        },  
        Rakshasa: {
          'Limited Magic Immunity': {
            name: 'Limited Magic Immunity',
            version: '1.0.0',
            authors: ['thatlonelybugbear', 'Elwin'],
          },
        },
      },
      modern: {
        Medusa: {
          'Petrifying Gaze': {
            name: 'Petrifying Gaze',
            version: '1.1.0',
            authors: ['Elwin'],
          },
        },
      },
    },
  });
}
