import { moduleName } from "./constants.ts";

export function setConfig() {
  foundry.utils.setProperty(CONFIG, moduleName, {
    module: moduleName,
    automations: {
      legacy: {
        "Absorbing Tattoo, Acid": {
          name: "Absorbing Tattoo, Acid",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Cold": {
          name: "Absorbing Tattoo, Cold",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Fire": {
          name: "Absorbing Tattoo, Fire",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Force": {
          name: "Absorbing Tattoo, Force",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Lightning": {
          name: "Absorbing Tattoo, Lightning",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Necrotic": {
          name: "Absorbing Tattoo, Necrotic",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Poison": {
          name: "Absorbing Tattoo, Poison",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Psychic": {
          name: "Absorbing Tattoo, Psychic",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Radiant": {
          name: "Absorbing Tattoo, Radiant",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Absorbing Tattoo, Thunder": {
          name: "Absorbing Tattoo, Thunder",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Accursed Specter": {
          name: "Accursed Specter",
          type: "Class Feature",
          version: "5.1.9",
          authors: ["Bacon"],
        },
        "Alchemist's Fire (flask)": {
          name: "Alchemist's Fire (flask)",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin"],
        },
        "Arms of the Astral Self": {
          name: "Arms of the Astral Self",
          type: "Class Feature",
          version: "2.3.0",
          authors: ["Elwin", "Spoob"],
        },
        "Arrow-Catching Shield": {
          name: "Arrow-Catching Shield",
          type: "Item",
          version: "4.2.0",
          authors: ["Elwin"],
        },
        Assassinate: {
          name: "Assassinate",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Subjekt H"],
        },
        "Awakened Astral Self": {
          name: "Awakened Astral Self",
          type: "Class Feature",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Body of the Astral Self": {
          name: "Body of the Astral Self",
          type: "Class Feature",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Bulwark of Force": {
          name: "Bulwark of Force",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Channel Divinity: Rebuke the Violent": {
          name: "Channel Divinity: Rebuke the Violent",
          type: "Class Feature",
          version: "2.3.0",
          authors: ["Elwin"],
        },
        "Channel Divinity: Vow of Enmity": {
          name: "Channel Divinity: Vow of Enmity",
          type: "Class Feature",
          version: "3.4.0",
          authors: ["Elwin"],
        },
        "Clockwork Amulet": {
          name: "Clockwork Amulet",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin", "thatlonelybugbear"],
        },
        "Corpse Slayer Weapon": {
          name: "Corpse Slayer Weapon",
          type: "Item",
          factory: true,
          version: "1.2.1",
          authors: ["Elwin", "SagaTympana"],
        },
        "Crown of Stars": {
          name: "Crown of Stars",
          type: "Spell",
          version: "2.1.0",
          authors: ["Elwin", "Bakana", "Xenophes"],
        },
        "Dagger of Venom": {
          name: "Dagger of Venom",
          type: "Item",
          version: "2.3.0",
          authors: ["Elwin"],
        },
        "Dampen Elements": {
          name: "Dampen Elements",
          type: "Class Feature",
          version: "2.0.3",
          authors: ["Elwin"],
        },
        "Deflect Missiles": {
          name: "Deflect Missiles",
          type: "Class Feature",
          version: "2.4.0",
          authors: ["Elwin", "Moto Moto", "thatlonelybugbear"],
        },
        "Divine Allegiance": {
          name: "Divine Allegiance",
          type: "Class Feature",
          version: "4.1.0",
          authors: ["Elwin"],
        },
        "Dragonhide Belt, +1": {
          name: "Dragonhide Belt, +1",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Drow Hand Crossbow": {
          name: "Drow Hand Crossbow",
          type: "Item",
          version: "1.1.1",
          authors: ["Elwin"],
        },
        "Drow Poison": {
          name: "Drow Poison",
          type: "Item",
          version: "2.0.3",
          authors: ["Elwin"],
        },
        "Drunkard's Luck": {
          name: "Drunkard's Luck",
          type: "Class Feature",
          version: "1.2.0",
          authors: ["Elwin"],
        },
        "Drunken Technique": {
          name: "Drunken Technique",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Eversmoking Bottle": {
          name: "Eversmoking Bottle",
          type: "Item",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Fighting Style: Great Weapon Fighting": {
          name: "Fighting Style: Great Weapon Fighting",
          type: "Class Feature",
          version: "1.3.0",
          authors: ["Elwin", "WurstKorn"],
        },
        "Flame Arrows": {
          name: "Flame Arrows",
          type: "Spell",
          version: "2.1.0",
          authors: ["Elwin", "Lin Dong"],
        },
        "Flames of Phlegethos": {
          name: "Flames of Phlegethos",
          type: "Feat",
          version: "3.2.0",
          authors: ["Elwin"],
        },
        "Flame Tongue Greatsword": {
          name: "Flame Tongue Greatsword",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Flame Tongue Longsword": {
          name: "Flame Tongue Longsword",
          type: "Item",
          version: "2.0.3",
          authors: ["Elwin"],
        },
        "Flame Tongue Rapier": {
          name: "Flame Tongue Rapier",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin", "Moto Moto"],
        },
        "Flame Tongue Scimitar": {
          name: "Flame Tongue Scimitar",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Flame Tongue Shortsword": {
          name: "Flame Tongue Shortsword",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Flash of Genius": {
          name: "Flash of Genius",
          type: "Class Feature",
          version: "2.2.0",
          authors: ["Elwin"],
        },
        Forage: {
          name: "Forage",
          type: "Generic Action",
          version: "1.2.0",
          authors: ["Fridan99", "Christopher"],
        },
        "Gift of the Metallic Dragon": {
          name: "Gift of the Metallic Dragon",
          type: "Feat",
          version: "4.3.0",
          authors: ["Elwin"],
        },
        Goodberry: {
          name: "Goodberry",
          type: "Spell",
          version: "3.4.0",
          authors: ["Elwin"],
        },
        "Great Weapon Master": {
          name: "Great Weapon Master",
          type: "Feat",
          version: "3.4.0",
          authors: ["Elwin"],
        },
        "Grenade, Smoke": {
          name: "Grenade, Smoke",
          type: "Item",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Guarded Mind": {
          name: "Guarded Mind",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Guardian Emblem": {
          name: "Guardian Emblem",
          type: "Item",
          version: "4.2.1",
          authors: ["Elwin"],
        },
        "Intoxicated Frenzy": {
          name: "Intoxicated Frenzy",
          type: "Class Feature",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Ki": {
          name: "Ki",
          type: "Class Feature",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Moon-Touched Greatsword": {
          name: "Moon-Touched Greatsword",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin", "Moto Moto"],
        },
        "Moon-Touched Longsword": {
          name: "Moon-Touched Longsword",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin", "Moto Moto"],
        },
        "Moon-Touched Rapier": {
          name: "Moon-Touched Rapier",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin", "Moto Moto"],
        },
        "Moon-Touched Scimitar": {
          name: "Moon-Touched Scimitar",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin", "Moto Moto"],
        },
        "Moon-Touched Shortsword": {
          name: "Moon-Touched Shortsword",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin", "Moto Moto"],
        },
        "Natural Armor": {
          name: "Natural Armor",
          type: "Race Feature",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Negative Energy Flood": {
          name: "Negative Energy Flood",
          type: "Spell",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        Oathbow: {
          name: "Oathbow",
          type: "Item",
          version: "2.3.0",
          authors: ["Elwin", "Christopher"],
        },
        "Poison, Basic (vial)": {
          name: "Poison, Basic (vial)",
          type: "Item",
          version: "2.0.1",
          authors: ["Elwin"],
        },
        Poisoner: {
          name: "Poisoner",
          type: "Class Features",
          version: "2.2.0",
          authors: ["Elwin"],
        },
        "Potent Poison": {
          name: "Potent Poison",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Produce Flame": {
          name: "Produce Flame",
          type: "Spell",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Psionic Power": {
          name: "Psionic Power",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Psionic Power: Protective Field": {
          name: "Psionic Power: Protective Field",
          type: "Class Feature",
          version: "4.2.0",
          authors: ["Elwin"],
        },
        "Purple Worm Poison": {
          name: "Purple Worm Poison",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        "Recall Monster Lore": {
          name: "Recall Monster Lore",
          type: "Generic Action",
          version: "1.0.1",
          authors: ["Elwin", "Fridan99"],
        },
        "Ring of Evasion": {
          name: "Ring of Evasion",
          type: "Item",
          version: "1.0.3",
          authors: ["Elwin"],
        },
        "Sentinel at Death's Door": {
          name: "Sentinel at Death's Door",
          type: "Class Feature",
          version: "4.1.1",
          authors: ["Elwin"],
        },
        "Serpent Venom": {
          name: "Serpent Venom",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
        Sharpshooter: {
          name: "Sharpshooter",
          type: "Feat",
          version: "3.1.0",
          authors: ["Elwin"],
        },
        "Shell Defense": {
          name: "Shell Defense",
          type: "Race Feature",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Shield of Missile Attraction": {
          name: "Shield of Missile Attraction",
          type: "Item",
          version: "2.2.0",
          authors: ["Elwin", "Ris"],
        },
        "Sorrowful Fate": {
          name: "Sorrowful Fate",
          type: "Class Feature",
          version: "2.2.1",
          authors: ["Elwin"],
        },
        "Spiny Shield": {
          name: "Spiny Shield",
          type: "Spell",
          version: "1.0.0",
          authors: ["tb"],
        },
        "Spirit Shield": {
          name: "Spirit Shield",
          type: "Class Feature",
          version: "4.3.0",
          authors: ["Elwin"],
        },
        "Steady Aim": {
          name: "Steady Aim",
          type: "Class Feature",
          version: "3.3.0",
          authors: ["Elwin"],
        },
        "Sun Blade": {
          name: "Sun Blade",
          type: "Item",
          version: "2.5.0",
          authors: ["Elwin"],
        },
        "Tasha's Mind Whip": {
          name: "Tasha's Mind Whip",
          type: "Spell",
          version: "2.0.1",
          authors: ["Elwin", "Moto Moto"],
        },
        "Telekinetic Adept": {
          name: "Telekinetic Adept",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Telekinetic Master": {
          name: "Telekinetic Master",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Tipsy Sway": {
          name: "Tipsy Sway",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Tomb of Levistus": {
          name: "Tomb of Levistus",
          aliases: ["Eldritch Invocations: Tomb of Levistus"],
          type: "Class Feature",
          version: "1.1.0",
          authors: ["Elwin", "pospa4"],
        },
        "Unwavering Mark": {
          name: "Unwavering Mark",
          type: "Class Feature",
          version: "3.5.0",
          authors: ["Elwin"],
        },
        "Vengeful Ancestors": {
          name: "Vengeful Ancestors",
          type: "Class Feature",
          version: "3.1.1",
          authors: ["Elwin"],
        },
        "Vigilant Guardian": {
          name: "Vigilant Guardian",
          type: "Race Feature",
          version: "4.2.0",
          authors: ["Elwin"],
        },
        "Visage of the Astral Self": {
          name: "Visage of the Astral Self",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Warding Flare": {
          name: "Warding Flare",
          type: "Class Feature",
          version: "3.3.0",
          authors: ["Elwin"],
        },
        "Warding Maneuver": {
          name: "Warding Maneuver",
          type: "Class Feature",
          version: "2.3.0",
          authors: ["Elwin"],
        },
        "Wyvern Poison": {
          name: "Wyvern Poison",
          type: "Item",
          version: "2.0.2",
          authors: ["Elwin"],
        },
      },
      modern: {
        "Adventurer's Ring": {
          name: "Adventurer's Ring",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Alchemist's Fire": {
          name: "Alchemist's Fire",
          type: "Item",
          version: "1.0.1",
          authors: ["Elwin"],
        },
        "Arrow-Catching Shield": {
          name: "Arrow-Catching Shield",
          type: "Item",
          version: "1.2.0",
          authors: ["Elwin"],
        },
        "Badge of the Watch": {
          name: "Badge of the Watch",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Bloodwell Vial, +1": {
          name: "Bloodwell Vial, +1",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Bracers of Celerity": {
          name: "Bracers of Celerity",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Cap of Vanishing": {
          name: "Cap of Vanishing",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Cloak of Billowing (Stranger Things)": {
          name: "Cloak of Billowing (Stranger Things)",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Clockwork Amulet": {
          name: "Clockwork Amulet",
          type: "Item",
          version: "1.0.2",
          authors: ["Elwin", "thatlonelybugbear"],
        },
        "Channel Divinity": {
          name: "Channel Divinity",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Channel Divinity: Vow of Enmity": {
          name: "Channel Divinity: Vow of Enmity",
          type: "Class Feature",
          version: "1.2.0",
          authors: ["Elwin"],
        },
        "Charger": {
          name: "Charger",
          type: "Feat",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Dagger of Venom": {
          name: "Dagger of Venom",
          type: "Item",
          version: "1.2.0",
          authors: ["Elwin"],
        },
        Deathdance: {
          name: "Deathdance",
          type: "Item",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Deflect Attacks": {
          name: "Deflect Attacks",
          type: "Class Feature",
          version: "1.4.0",
          authors: ["Elwin"],
        },
        "Dread Helm (Stranger Things)": {
          name: "Dread Helm (Stranger Things)",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Eversmoking Bottle": {
          name: "Eversmoking Bottle",
          type: "Item",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Flame Tongue": {
          name: "Flame Tongue",
          type: "Item",
          factory: true,
          version: "1.0.3",
          authors: ["Elwin"],
        },
        Goodberry: {
          name: "Goodberry",
          type: "Spell",
          version: "1.3.0",
          authors: ["Elwin"],
        },
        "Great Weapon Fighting": {
          name: "Great Weapon Fighting",
          type: "Feat",
          version: "1.3.0",
          authors: ["Elwin", "WurstKorn"],
        },
        "Great Weapon Master": {
          name: "Great Weapon Master",
          type: "Feat",
          version: "1.5.0",
          authors: ["Elwin"],
        },
        "Innate Sorcery": {
          name: "Innate Sorcery",
          type: "Class Feature",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Smoke Grenade": {
          name: "Smoke Grenade",
          type: "Item",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Improved Warding Flare": {
          name: "Improved Warding Flare",
          type: "Class Feature",
          version: "1.0.1",
          authors: ["Elwin"],
        },
        "Lamannian Oak Focus": {
          name: "Lamannian Oak Focus",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Lolth’s Sting": {
          name: "Lolth’s Sting",
          aliases: ["Lolth's Sting"],
          type: "Item",
          version: "1.0.1",
          authors: ["Elwin"],
        },
        Oathbow: {
          name: "Oathbow",
          type: "Item",
          factory: true,
          version: "2.3.0",
          authors: ["Elwin", "Christopher"],
        },
        "Oil of Etherealness": {
          name: "Oil of Etherealness",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Poison, Basic": {
          name: "Poison, Basic",
          type: "Item",
          version: "1.0.2",
          authors: ["Elwin"],
        },
        Poisoner: {
          name: "Poisoner",
          type: "Feat",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Potent Poison": {
          name: "Potent Poison",
          type: "Item",
          version: "1.0.1",
          authors: ["Elwin"],
        },
        "Potion of Heroism": {
          name: "Potion of Heroism",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Potion of Pugilism": {
          name: "Potion of Pugilism",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Produce Flame": {
          name: "Produce Flame",
          type: "Spell",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Purple Worm Poison": {
          name: "Purple Worm Poison",
          type: "Item",
          version: "1.0.1",
          authors: ["Elwin"],
        },
        "Ring of Evasion": {
          name: "Ring of Evasion",
          type: "Item",
          version: "1.0.3",
          authors: ["Elwin"],
        },
        "Rod of the Pact Keeper, +1": {
          name: "Rod of the Pact Keeper, +1",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Serpent Venom": {
          name: "Serpent Venom",
          type: "Item",
          version: "1.0.1",
          authors: ["Elwin"],
        },
        Sharpshooter: {
          name: "Sharpshooter",
          type: "Feat",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Shield of Missile Attraction": {
          name: "Shield of Missile Attraction",
          type: "Item",
          version: "1.2.0",
          authors: ["Elwin", "Ris"],
        },
        "Spiked Shield": {
          name: "Spiked Shield",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Steady Aim": {
          name: "Steady Aim",
          type: "Class Feature",
          version: "1.2.0",
          authors: ["Elwin"],
        },
        "Sun Blade": {
          name: "Sun Blade",
          type: "Item",
          version: "1.4.0",
          authors: ["Elwin"],
        },
        "Sword of Wounding": {
          name: "Sword of Wounding",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        Ulcrun: {
          name: "Ulcrun",
          type: "Item",
          version: "1.0.0",
          authors: ["Elwin"],
        },
        "Wand of Paralysis": {
          name: "Wand of Paralysis",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Warding Flare": {
          name: "Warding Flare",
          type: "Class Feature",
          version: "1.1.0",
          authors: ["Elwin"],
        },
        "Wraps of Unarmed Power, +1": {
          name: "Wraps of Unarmed Power, +1",
          type: "Item",
          version: "1.0.0",
          authors: ["Moto Moto"],
        },
        "Wyvern Poison": {
          name: "Wyvern Poison",
          type: "Item",
          version: "1.0.1",
          authors: ["Elwin"],
        },
      },
    },
    monsterAutomations: {
      legacy: {
        "Goblin Psi Commander": {
          "Psionic Shield": {
            name: "Psionic Shield",
            version: "2.2.0",
            authors: ["Elwin"],
          },
        },
        Lich: {
          "Negative Energy Tether": {
            name: "Negative Energy Tether",
            version: "2.1.0",
            authors: ["Elwin"],
          },
        },
        Medusa: {
          "Petrifying Gaze": {
            name: "Petrifying Gaze",
            version: "1.1.1",
            authors: ["Elwin", "Moto Moto"],
          },
        },
        Rakshasa: {
          "Limited Magic Immunity": {
            name: "Limited Magic Immunity",
            version: "1.2.0",
            authors: ["thatlonelybugbear", "Elwin"],
          },
        },
      },
      modern: {
        Medusa: {
          "Petrifying Gaze": {
            name: "Petrifying Gaze",
            version: "1.1.1",
            authors: ["Elwin"],
          },
        },
        "Goblin Boss": {
          "Redirect Attack": {
            name: "Redirect Attack",
            version: "1.0.0",
            authors: ["TMinz"],
          },
        },
      },
    },
  });
}
