import { moduleName } from './constants.js';

export function setConfig() {
  foundry.utils.setProperty(CONFIG, moduleName, {
    module: moduleName,
    automations: {
      legacy: {
        'Absorbing Tattoo, Acid': {
          name: 'Absorbing Tattoo, Acid',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Cold': {
          name: 'Absorbing Tattoo, Cold',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Fire': {
          name: 'Absorbing Tattoo, Fire',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Force': {
          name: 'Absorbing Tattoo, Force',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Lightning': {
          name: 'Absorbing Tattoo, Lightning',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Necrotic': {
          name: 'Absorbing Tattoo, Necrotic',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Poison': {
          name: 'Absorbing Tattoo, Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Psychic': {
          name: 'Absorbing Tattoo, Psychic',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Radiant': {
          name: 'Absorbing Tattoo, Radiant',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Absorbing Tattoo, Thunder': {
          name: 'Absorbing Tattoo, Thunder',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        "Alchemist's Fire (flask)": {
          name: "Alchemist's Fire (flask)",
          type: 'Item',
          version: '2.0.0',
          authors: ['Elwin'],
        },
        'Arrow-Catching Shield': {
          name: 'Arrow-Catching Shield',
          type: 'Item',
          version: '4.0.2',
          authors: ['Elwin'],
        },
        'Channel Divinity: Rebuke the Violent': {
          name: 'Channel Divinity: Rebuke the Violent',
          type: 'Class Feature',
          version: '2.1.0',
          authors: ['Elwin'],
        },
        'Channel Divinity: Vow of Enmity': {
          name: 'Channel Divinity: Vow of Enmity',
          type: 'Class Feature',
          version: '3.0.1',
          authors: ['Elwin'],
        },
        'Dagger of Venom': {
          name: 'Dagger of Venom',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Dampen Elements': {
          name: 'Dampen Elements',
          type: 'Class Feature',
          version: '2.0.2',
          authors: ['Elwin'],
        },
        'Divine Allegiance': {
          name: 'Divine Allegiance',
          type: 'Class Feature',
          version: '4.0.1',
          authors: ['Elwin'],
        },
        'Drow Hand Crossbow': {
          name: 'Drow Hand Crossbow',
          type: 'Item',
          version: '1.1.0',
          authors: ['Elwin'],
        },
        'Drow Poison': {
          name: 'Drow Poison',
          type: 'Item',
          version: '2.0.2',
          authors: ['Elwin'],
        },
        'Flames of Phlegethos': {
          name: 'Flames of Phlegethos',
          type: 'Feat',
          version: '3.1.0',
          authors: ['Elwin'],
        },
        'Flash of Genius': {
          name: 'Flash of Genius',
          type: 'Class Feature',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Gift of the Metallic Dragon': {
          name: 'Gift of the Metallic Dragon',
          type: 'Feat',
          version: '4.1.0',
          authors: ['Elwin'],
        },
        Goodberry: {
          name: 'Goodberry',
          type: 'Spell',
          version: '3.1.0',
          authors: ['Elwin'],
        },
        'Great Weapon Master': {
          name: 'Great Weapon Master',
          type: 'Feat',
          version: '3.0.2',
          authors: ['Elwin'],
        },
        'Guardian Emblem': {
          name: 'Guardian Emblem',
          type: 'Item',
          version: '4.1.0',
          authors: ['Elwin'],
        },
        'Poison, Basic (vial)': {
          name: 'Poison, Basic (vial)',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        Poisoner: {
          name: 'Poisoner',
          type: 'Class Features',
          version: '2.1.1',
          authors: ['Elwin'],
        },
        'Potent Poison': {
          name: 'Potent Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        'Psionic Power: Protective Field': {
          name: 'Psionic Power: Protective Field',
          type: 'Class Feature',
          version: '4.0.1',
          authors: ['Elwin'],
        },
        'Purple Worm Poison': {
          name: 'Purple Worm Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        "Sentinel at Death's Door": {
          name: "Sentinel at Death's Door",
          type: 'Class Feature',
          version: '4.0.1',
          authors: ['Elwin'],
        },
        'Serpent Venom': {
          name: 'Serpent Venom',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
        Sharpshooter: {
          name: 'Sharpshooter',
          type: 'Feat',
          version: '3.0.2',
          authors: ['Elwin'],
        },
        'Sorrowful Fate': {
          name: 'Sorrowful Fate',
          type: 'Class Feature',
          version: '2.1.0',
          authors: ['Elwin'],
        },
        'Spirit Shield': {
          name: 'Spirit Shield',
          type: 'Class Feature',
          version: '4.0.1',
          authors: ['Elwin'],
        },
        'Steady Aim': {
          name: 'Steady Aim',
          type: 'Class Feature',
          version: '3.0.1',
          authors: ['Elwin'],
        },
        'Sun Blade': {
          name: 'Sun Blade',
          type: 'Item',
          version: '2.1.0',
          authors: ['Elwin'],
        },
        'Unwavering Mark': {
          name: 'Unwavering Mark',
          type: 'Class Feature',
          version: '3.0.2',
          authors: ['Elwin'],
        },
        'Vengeful Ancestors': {
          name: 'Vengeful Ancestors',
          type: 'Class Feature',
          version: '3.0.1',
          authors: ['Elwin'],
        },
        'Vigilant Guardian': {
          name: 'Vigilant Guardian',
          type: 'Race Feature',
          version: '4.0.1',
          authors: ['Elwin'],
        },
        'Warding Flare': {
          name: 'Warding Flare',
          type: 'Class Feature',
          version: '3.0.1',
          authors: ['Elwin'],
        },
        'Warding Maneuver': {
          name: 'Warding Maneuver',
          type: 'Class Feature',
          version: '2.1.0',
          authors: ['Elwin'],
        },
        'Wyvern Poison': {
          name: 'Wyvern Poison',
          type: 'Item',
          version: '2.0.1',
          authors: ['Elwin'],
        },
      },
      modern: {
        "Alchemist's Fire": {
          name: "Alchemist's Fire",
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Arrow-Catching Shield': {
          name: 'Arrow-Catching Shield',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Dagger of Venom': {
          name: 'Dagger of Venom',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        Goodberry: {
          name: 'Goodberry',
          type: 'Spell',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Great Weapon Master': {
          name: 'Great Weapon Master',
          type: 'Feat',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        "Lolth's Sting": {
          name: "Lolth's Sting",
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Poison, Basic': {
          name: 'Poison, Basic',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        Poisoner: {
          name: 'Poisoner',
          type: 'Feat',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Potent Poison': {
          name: 'Potent Poison',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Purple Worm Poison': {
          name: 'Purple Worm Poison',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Serpent Venom': {
          name: 'Serpent Venom',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Sharpshooter': {
          name: 'Sharpshooter',
          type: 'Feat',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Sun Blade': {
          name: 'Sun Blade',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
        'Wyvern Poison': {
          name: 'Wyvern Poison',
          type: 'Item',
          version: '1.0.0',
          authors: ['Elwin'],
        },
      },
    },
    monsterAutomations: {
      legacy: {
        'Goblin Psi Commander': {
          'Psionic Shield': {
            name: 'Psionic Shield',
            version: '2.1.0',
            authors: ['Elwin'],
          },
        },
        Lich: {
          'Negative Energy Tether': {
            name: 'Negative Energy Tether',
            version: '2.0.1',
            authors: ['Elwin'],
          },
        },
      },
      modern: {},
    },
  });
}
