import { moduleName } from './constants.js';

export function setConfig() {
  setProperty(CONFIG, moduleName, {
    module: moduleName,
    automations: {
      'Absorb Elements': {
        name: 'Absorb Elements',
        type: 'Spell',
        version: '1.0.2',
        authors: ['Bradeck', 'thatlonelybugbear'],
      },
      'All of Nothing Armor': {
        name: 'All of Nothing Armor',
        type: 'Item',
        homebrew: true,
        version: '0.1.1',
        authors: ['CoolHand'],
      },
      'Arrow-Catching Shield': {
        name: 'Arrow-Catching Shield',
        type: 'Item',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Aspect of the Beast: Bear': {
        name: 'Aspect of the Beast: Bear',
        type: 'Class Feature',
        version: '1.0.0',
        authors: ['Moto Moto'],
      },
      Bless: {
        name: 'Bless',
        type: 'Spell',
        version: '0.1.1',
        authors: ['Moto Moto'],
      },
      'Blessed Healer': {
        name: 'Blessed Healer',
        type: 'Class Feature',
        version: '1.0.1',
        authors: ['SagaTympana, Moto Moto'],
      },
      'Borrowed Knowledge': {
        name: 'Borrowed Knowledge',
        type: 'Spell',
        version: '0.1.1',
        authors: ['SagaTympana'],
      },
      'Channel Divinity: Divine Spark': {
        name: 'Channel Divinity: Divine Spark',
        type: 'Class Feature',
        UA: true,
        version: '0.1.1',
        authors: ['SagaTympana'],
      },
      'Channel Divinity: Turn the Tide': {
        name: 'Channel Divinity: Turn the Tide',
        type: 'Class Feature',
        version: '1.0.1',
        authors: ['Christopher'],
      },
      'Clockwork Amulet': {
        name: 'Clockwork Amulet',
        type: 'Item',
        version: '0.1.1',
        authors: ['thatlonelybugbear'],
      },
      'Corpse Slayer Longbow': {
        name: 'Corpse Slayer Longbow',
        type: 'Item',
        version: '0.1.1',
        authors: ['SagaTympana'],
      },
      Countercharm: {
        name: 'Countercharm',
        type: 'Class Feature',
        version: '1.0.1',
        authors: ['Moto Moto'],
      },
      'Crown of Stars': {
        name: 'Crown of Stars',
        type: 'Spell',
        version: '1.0.1',
        authors: ['Xenophes'],
      },
      'Deflect Missiles': {
        name: 'Deflect Missiles',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Deflect Missiles Attack': {
        name: 'Deflect Missiles Attack',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Deft Strike': {
        name: 'Deft Strike',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Divine Allegiance': {
        name: 'Divine Allegiance',
        type: 'Class Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      Driftglobe: {
        name: 'Driftglobe',
        type: 'Item',
        version: '0.1.1',
        authors: ['buttcheeksio'],
      },
      'Dungeon Delver': {
        name: 'Dungeon Delver',
        type: 'Feat',
        version: '0.1.1',
        authors: ['TMinz'],
      },
      'Dust of Dryness': {
        name: 'Dust of Dryness',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Dust of Sneezing and Choking': {
        name: 'Dust of Sneezing and Choking',
        type: 'Item',
        version: '1.0.0',
        authors: ['SaltyJ'],
      },
      'Eldritch Cannon': {
        name: 'Eldritch Cannon',
        type: 'Class Feature',
        version: '0.1.1',
        authors: ['allgoodtogrow'],
      },
      Elusive: {
        name: 'Elusive',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['SagaTympana'],
      },
      'Eyes of Minute Seeing': {
        name: 'Eyes of Minute Seeing',
        type: 'Item',
        version: '1.9.0',
        authors: ['Moto Moto'],
      },
      'Fighting Style: Great Weapon Fighting': {
        name: 'Fighting Style: Great Weapon Fighting',
        type: 'Class Feature',
        version: '0.1.3',
        authors: ['WurstKorn'],
      },
      'Flames of Phlegethos': {
        name: 'Flames of Phlegethos',
        type: 'Feat',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Flaming Sphere': {
        name: 'Flaming Sphere',
        type: 'Spell',
        version: '1.0.2',
        authors: ['Moto Moto'],
      },
      'Flash of Genius': {
        name: 'Flash of Genius',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['SagaTympana'],
      },
      Forage: {
        name: 'Forage',
        type: 'Generic Action',
        version: '0.1.1',
        authors: ['Fridan99', 'Christopher'],
      },
      'Gift of Alacrity': {
        name: 'Gift of Alacrity',
        type: 'Spell',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Gift of the Metallic Dragon': {
        name: 'Gift of the Metallic Dragon',
        type: 'Feat',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Goggles of Object Reading': {
        name: 'Goggles of Object Reading',
        type: 'Item',
        version: '1.0.0',
        authors: ['Moto Moto'],
      },
      Goodberry: {
        name: 'Goodberry',
        type: 'Spell',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Great Weapon Master': {
        name: 'Great Weapon Master',
        type: 'Feat',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Great Weapon Master Attack': {
        name: 'Great Weapon Master Attack',
        type: 'Feat',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Guardian Emblem': {
        name: 'Guardian Emblem',
        type: 'Item',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      Healer: {
        name: 'Healer',
        type: 'Feat',
        version: '0.1.1',
        authors: ['SagaTympana', 'WurstKorn'],
      },
      'Hero Points': {
        name: 'Hero Points',
        type: 'Generic Feature',
        version: '1.0.0',
        authors: ['Moto Moto'],
      },
      Immolation: {
        name: 'Immolation',
        type: 'Spell',
        version: '0.1.0',
        authors: ['Moto Moto', 'SagaTympana', 'Worthlesston'],
      },
      'Indomitable Might': {
        name: 'Indomitable Might',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['Muhammad2126'],
      },
      "Lila's Famous Mushroom Tea": {
        name: "Lila's Famous Mushroom Tea",
        type: 'Item',
        homebrew: true,
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Magic Stone': {
        name: 'Magic Stone',
        type: 'Spell',
        version: '0.1.2',
        authors: ['Bradeck', 'Coolhand', 'SagaTympana'],
      },
      'Medium Armor Master': {
        name: 'Medium Armor Master',
        type: 'Feat',
        version: '0.1.0',
        authors: ['Muhammad2126'],
      },
      'Memorize Spell': {
        name: 'Memorize Spell',
        type: 'Class Feature',
        UA: true,
        version: '0.1.1',
        authors: ['SagaTympana'],
      },
      'Meteor Swarm': {
        name: 'Meteor Swarm',
        type: 'Spell',
        version: '1.0.1',
        authors: ['Xenophes'],
      },
      Mislead: {
        name: 'Mislead',
        type: 'Spell',
        version: '0.1.2',
        authors: ['TMinz'],
      },
      'Moon-Touched Sword, Greatsword': {
        name: 'Moon-Touched Sword, Greatsword',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Moon-Touched Sword, Longsword': {
        name: 'Moon-Touched Sword, Longsword',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Moon-Touched Sword, Scimitar': {
        name: 'Moon-Touched Sword, Scimitar',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Moon-Touched Sword, Shortsword': {
        name: 'Moon-Touched Sword, Shortsword',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Moon-Touched, Rapier': {
        name: 'Moon-Touched, Rapier',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      "Mordenkainen's Sword": {
        name: "Mordenkainen's Sword",
        type: 'Spell',
        version: '0.1.1',
        authors: ['Janner3D'],
      },
      Net: {
        name: 'Net',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      Oathbow: {
        name: 'Oathbow',
        type: 'Item',
        version: '1.0.1',
        authors: ['Christopher'],
      },
      Poisoner: {
        name: 'Poisoner',
        type: 'Feat',
        version: '0.1.2',
        authors: ['WurstKorn'],
      },
      'Potion of Healing': {
        name: 'Potion of Healing',
        type: 'Item',
        homebrew: true,
        version: '0.1.1',
        authors: ['TreeDragon', 'thatlonelybugbear'],
      },
      'Potion of Healing (Greater)': {
        name: 'Potion of Healing (Greater)',
        type: 'Item',
        homebrew: true,
        version: '0.1.1',
        authors: ['TreeDragon', 'thatlonelybugbear'],
      },
      'Potion of Healing (Superior)': {
        name: 'Potion of Healing (Superior)',
        type: 'Item',
        homebrew: true,
        version: '0.1.1',
        authors: ['TreeDragon', 'thatlonelybugbear'],
      },
      'Potion of Healing (Supreme)': {
        name: 'Potion of Healing (Supreme)',
        type: 'Item',
        homebrew: true,
        version: '0.1.1',
        authors: ['TreeDragon', 'thatlonelybugbear'],
      },
      'Power Word Pain': {
        name: 'Power Word Pain',
        type: 'Spell',
        version: '0.1.1',
        authors: ['Xenophes'],
      },
      'Primal Champion': {
        name: 'Primal Champion',
        type: 'Class Feature',
        version: '0.1.0',
        authors: ['Muhammad2126'],
      },
      'Protection from Poison': {
        name: 'Protection from Poison',
        type: 'Spell',
        version: '1.0.0',
        authors: ['Moto Moto'],
      },
      'Psionic Power: Protective Field': {
        name: 'Psionic Power: Protective Field',
        type: 'Class Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Raise Dead': {
        name: 'Raise Dead',
        type: 'Spell',
        version: '0.1.0',
        authors: ['SagaTympana'],
      },
      'Recall Monster Lore': {
        name: 'Recall Monster Lore',
        type: 'Generic Action',
        version: '0.1.1',
        authors: ['Fridan99'],
      },
      Resurrection: {
        name: 'Resurrection',
        type: 'Spell',
        version: '0.1.0',
        authors: ['SagaTympana'],
      },
      'Ryath Root': {
        name: 'Ryath Root',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Scaled Ornament (stirring)': {
        name: 'Scaled Ornament (stirring)',
        type: 'Item',
        version: '0.1.0',
        authors: ['Muhammad2126'],
      },
      "Sentinel at Death's Door": {
        name: "Sentinel at Death's Door",
        type: 'Class Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      Sharpshooter: {
        name: 'Sharpshooter',
        type: 'Feat',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      'Shield of Missile Attraction': {
        name: 'Shield of Missile Attraction',
        type: 'Item',
        version: '1.0.0',
        authors: ['Ris'],
      },
      Slow: {
        name: 'Slow',
        type: 'Spell',
        version: '1.0.2',
        authors: ['Moto Moto'],
      },
      Snare: {
        name: 'Snare',
        type: 'Spell',
        version: '0.1.0',
        authors: ['Quinn Dexter'],
      },
      'Sorcerous Burst': {
        name: 'Sorcerous Burst',
        type: 'Spell',
        UA: true,
        version: '1.0.1',
        authors: ['SagaTympana'],
      },
      'Soul of Artifice': {
        name: 'Soul of Artifice',
        type: 'Class Feature',
        version: '0.1.1',
        authors: ['SagaTympana'],
      },
      'Spirit Shield': {
        name: 'Spirit Shield',
        type: 'Class Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Spirit Totem: Bear Spirit': {
        name: 'Spirit Totem: Bear Spirit',
        type: 'Class Feature',
        version: '0.1.1',
        authors: ['Moto Moto'],
      },
      'Starry Wisp': {
        name: 'Starry Wisp',
        type: 'Spell',
        UA: true,
        version: '0.1.0',
        authors: ['SagaTympana'],
      },
      'Steady Aim': {
        name: 'Steady Aim',
        type: 'Class Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Tomb of Levistus': {
        name: 'Tomb of Levistus',
        type: 'Class Feature',
        version: '0.1.2',
        authors: ['pospa4'],
      },
      'Toughened Skin': {
        name: 'Toughened Skin',
        type: 'Feat',
        homebrew: true,
        version: '0.1.0',
        authors: ['Muhammad2126'],
      },
      'Unwavering Mark': {
        name: 'Unwavering Mark',
        type: 'Class Feature',
        version: '2.0.2',
        authors: ['Elwin'],
      },
      'Vengeful Ancertors': {
        name: 'Vengeful Ancertors',
        type: 'Class Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      Vial: {
        name: 'Vial',
        type: 'Item',
        version: '1.0.0',
        authors: ['Moto Moto'],
      },
      'Vigilant Guardian': {
        name: 'Vigilant Guardian',
        type: 'Race Feature',
        version: '2.0.1',
        authors: ['Elwin'],
      },
      'Wand of Winter': {
        name: 'Wand of Winter',
        type: 'Item',
        version: '0.1.1',
        authors: ['thatlonelybugbear'],
      },
      'Wukka Nuts': {
        name: 'Wukka Nuts',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
      Wildroot: {
        name: 'Wildroot',
        type: 'Item',
        version: '0.1.0',
        authors: ['Moto Moto'],
      },
    },
    monsterAutomations: {
      Banshee: {
        Wail: {
          name: 'Wail',
          version: '0.1.1',
          authors: ['Moto Moto'],
        },
        'Horrifying Visage': {
          name: 'Horrifying Visage',
          version: '0.1.1',
          authors: ['Moto Moto'],
        },
      },
      Beholder: {
        'Charm Ray': {
          name: 'Charm Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Death Ray': {
          name: 'Death Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Disintegration Ray': {
          name: 'Disintegration Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Enervation Ray': {
          name: 'Enervation Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Eye Rays': {
          name: 'Eye Rays',
          version: '0.1.1',
          authors: ['Christopher'],
        },
        'Eye Rays (Legendary)': {
          name: 'Eye Rays (Legendary)',
          version: '0.1.1',
          authors: ['Christopher'],
        },
        'Fear Ray': {
          name: 'Fear Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Paralyzing Ray': {
          name: 'Paralyzing Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Petrification Ray': {
          name: 'Petrification Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Sleep Ray': {
          name: 'Sleep Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Slowing Ray': {
          name: 'Slowing Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
        'Telekinetic Ray': {
          name: 'Telekinetic Ray',
          version: '0.1.0',
          authors: ['Christopher'],
        },
      },
      'Giant Spider': {
        Web: {
          name: 'Web',
          version: '0.1.0',
          authors: ['CoolHand'],
        },
      },
      'Hundred-Handed One': {
        Reactive: {
          name: 'Reactive',
          version: '0.1.0',
          authors: ['Muhammad2126'],
        },
      },
      Marilith: {
        Reactive: {
          name: 'Reactive',
          version: '0.1.0',
          authors: ['Muhammad2126'],
        },
      },
      'Marilith (Summoner Variant)': {
        Reactive: {
          name: 'Reactive',
          version: '0.1.0',
          authors: ['Muhammad2126'],
        },
      },
      'Shield Guardian': {
        'Spell Storing': {
          name: 'Spell Storing',
          version: '1.0.1',
          authors: ['n3veruary'],
        },
      },
      Spectator: {
        'Confusion Ray': {
          name: 'Confusion Ray',
          version: '0.1.0',
          authors: ['TMinz'],
        },
        'Fear Ray': {
          name: 'Fear Ray',
          version: '0.1.0',
          authors: ['TMinz'],
        },
        'Paralyzing Ray': {
          name: 'Paralyzing Ray',
          version: '0.1.0',
          authors: ['TMinz'],
        },
        'Spell Reflection': {
          name: 'Spell Reflection',
          version: '0.1.0',
          authors: ['TMinz'],
        },
        'Wounding Ray': {
          name: 'Wounding Ray',
          version: '0.1.0',
          authors: ['TMinz'],
        },
      },
      'Spider King': {
        Web: {
          name: 'Web',
          version: '0.1.0',
          authors: ['CoolHand'],
        },
      },
      'Vampire Spawn': {
        Bite: {
          name: 'Bite',
          version: '0.1.1',
          authors: ['Moto Moto'],
        },
      },
      Vrock: {
        Spores: {
          name: 'Spores',
          version: '0.1.0',
          authors: ['natesummers#8576'],
        },
        'Stunning Screech': {
          name: 'Stunning Screech',
          version: '0.1.0',
          authors: ['Muhammad2126'],
        },
      },
      'Vrock (Summoner Variant)': {
        Spores: {
          name: 'Spores',
          version: '0.1.0',
          authors: ['natesummers#8576'],
        },
        'Stunning Screech': {
          name: 'Stunning Screech',
          version: '0.1.0',
          authors: ['Muhammad2126'],
        },
      },
    },
  });
}
