import type { AutomationConfig } from "./_types.ts";
import { moduleName } from "./constants.ts";

export const automationConfig: AutomationConfig = {
  module: moduleName,
  automations: {
    legacy: {
      "Absorbing Tattoo, Acid": {
        name: "Absorbing Tattoo, Acid",
        identifier: "absorbing-tattoo-acid",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Cold": {
        name: "Absorbing Tattoo, Cold",
        identifier: "absorbing-tattoo-cold",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Fire": {
        name: "Absorbing Tattoo, Fire",
        identifier: "absorbing-tattoo-fire",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Force": {
        name: "Absorbing Tattoo, Force",
        identifier: "absorbing-tattoo-force",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Lightning": {
        name: "Absorbing Tattoo, Lightning",
        identifier: "absorbing-tattoo-lightning",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Necrotic": {
        name: "Absorbing Tattoo, Necrotic",
        identifier: "absorbing-tattoo-necrotic",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Poison": {
        name: "Absorbing Tattoo, Poison",
        identifier: "absorbing-tattoo-poison",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Psychic": {
        name: "Absorbing Tattoo, Psychic",
        identifier: "absorbing-tattoo-psychic",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Radiant": {
        name: "Absorbing Tattoo, Radiant",
        identifier: "absorbing-tattoo-radiant",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Absorbing Tattoo, Thunder": {
        name: "Absorbing Tattoo, Thunder",
        identifier: "absorbing-tattoo-thunder",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Accursed Specter": {
        name: "Accursed Specter",
        identifier: "accursed-specter",
        type: "Class Feature",
        version: "6.0.0",
        authors: ["Bacon"],
      },
      "Alchemist's Fire (flask)": {
        name: "Alchemist's Fire (flask)",
        identifier: "alchemists-fire-flask",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Arms of the Astral Self": {
        name: "Arms of the Astral Self",
        identifier: "arms-of-the-astral-self",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin", "Spoob"],
      },
      "Arrow-Catching Shield": {
        name: "Arrow-Catching Shield",
        identifier: "arrow-catching-shield",
        type: "Item",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      Assassinate: {
        name: "Assassinate",
        identifier: "assassinate",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Subjekt H"],
      },
      "Awakened Astral Self": {
        name: "Awakened Astral Self",
        identifier: "awakened-astral-self",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Badge of the Watch": {
        name: "Badge of the Watch",
        identifier: "badge-of-the-watch",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Body of the Astral Self": {
        name: "Body of the Astral Self",
        identifier: "body-of-the-astral-self",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Bloodwell Vial, +1": {
        name: "Bloodwell Vial, +1",
        identifier: "bloodwell-vial-1",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Bracers of Celerity": {
        name: "Bracers of Celerity",
        identifier: "bracers-of-celerity",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Bulwark of Force": {
        name: "Bulwark of Force",
        identifier: "bulwark-of-force",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Channel Divinity: Rebuke the Violent": {
        name: "Channel Divinity: Rebuke the Violent",
        identifier: "channel-divinity-rebuke-the-violent",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Channel Divinity: Vow of Enmity": {
        name: "Channel Divinity: Vow of Enmity",
        identifier: "channel-divinity-vow-of-enmity",
        type: "Class Feature",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Clockwork Amulet": {
        name: "Clockwork Amulet",
        identifier: "clockwork-amulet",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "thatlonelybugbear"],
      },
      "Corpse Slayer Weapon": {
        name: "Corpse Slayer Weapon",
        identifier: "corpse-slayer-weapon",
        type: "Item",
        factory: true,
        version: "2.0.0",
        authors: ["Elwin", "SagaTympana"],
      },
      "Crown of Stars": {
        name: "Crown of Stars",
        identifier: "crown-of-stars",
        type: "Spell",
        version: "3.0.0",
        authors: ["Elwin", "Bakana", "Xenophes"],
      },
      "Dagger of Venom": {
        name: "Dagger of Venom",
        identifier: "dagger-of-venom",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Dampen Elements": {
        name: "Dampen Elements",
        identifier: "dampen-elements",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Deflect Missiles": {
        name: "Deflect Missiles",
        identifier: "deflect-missiles",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto", "thatlonelybugbear"],
      },
      "Divine Allegiance": {
        name: "Divine Allegiance",
        identifier: "divine-allegiance",
        type: "Class Feature",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      "Dragonhide Belt, +1": {
        name: "Dragonhide Belt, +1",
        identifier: "dragonhide-belt-1",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Drow Hand Crossbow": {
        name: "Drow Hand Crossbow",
        identifier: "drow-hand-crossbow",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Drow Poison": {
        name: "Drow Poison",
        identifier: "drow-poison",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Drunkard's Luck": {
        name: "Drunkard's Luck",
        identifier: "drunkards-luck",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Drunken Technique": {
        name: "Drunken Technique",
        identifier: "drunken-technique",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Eversmoking Bottle": {
        name: "Eversmoking Bottle",
        identifier: "eversmoking-bottle",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Fighting Style: Great Weapon Fighting": {
        name: "Fighting Style: Great Weapon Fighting",
        identifier: "fighting-style-great-weapon-fighting",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin", "WurstKorn"],
      },
      "Flame Arrows": {
        name: "Flame Arrows",
        identifier: "flame-arrows",
        type: "Spell",
        version: "3.0.0",
        authors: ["Elwin", "Lin Dong"],
      },
      "Flames of Phlegethos": {
        name: "Flames of Phlegethos",
        identifier: "flames-of-phlegethos",
        type: "Feat",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Flame Tongue Greatsword": {
        name: "Flame Tongue Greatsword",
        identifier: "flame-tongue-greatsword",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Flame Tongue Longsword": {
        name: "Flame Tongue Longsword",
        identifier: "flame-tongue-longsword",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Flame Tongue Rapier": {
        name: "Flame Tongue Rapier",
        identifier: "flame-tongue-rapier",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Flame Tongue Scimitar": {
        name: "Flame Tongue Scimitar",
        identifier: "flame-tongue-scimitar",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Flame Tongue Shortsword": {
        name: "Flame Tongue Shortsword",
        identifier: "flame-tongue-shortsword",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Flash of Genius": {
        name: "Flash of Genius",
        identifier: "flash-of-genius",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      Forage: {
        name: "Forage",
        identifier: "forage",
        type: "Generic Action",
        version: "2.0.0",
        authors: ["Fridan99", "Christopher"],
      },
      "Gift of the Metallic Dragon": {
        name: "Gift of the Metallic Dragon",
        identifier: "gift-of-the-metallic-dragon",
        type: "Feat",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      "Gloves of Missile Snaring": {
        name: "Gloves of Missile Snaring",
        identifier: "gloves-of-missile-snaring",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Goodberry: {
        name: "Goodberry",
        identifier: "goodberry",
        type: "Spell",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Great Weapon Master": {
        name: "Great Weapon Master",
        identifier: "great-weapon-master",
        type: "Feat",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Grenade, Smoke": {
        name: "Grenade, Smoke",
        identifier: "grenade-smoke",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Guarded Mind": {
        name: "Guarded Mind",
        identifier: "guarded-mind",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Guardian Emblem": {
        name: "Guardian Emblem",
        identifier: "guardian-emblem",
        type: "Item",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      Healer: {
        name: "Healer",
        identifier: "healer",
        type: "Feat",
        version: "2.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Healer's Kit": {
        name: "Healer's Kit",
        identifier: "healers-kit",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Intoxicated Frenzy": {
        name: "Intoxicated Frenzy",
        identifier: "intoxicated-frenzy",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Ki: {
        name: "Ki",
        identifier: "ki",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Lamannian Oak Focus": {
        name: "Lamannian Oak Focus",
        identifier: "lamannian-oak-focus",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Moon-Touched Greatsword": {
        name: "Moon-Touched Greatsword",
        identifier: "moon-touched-greatsword",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Moon-Touched Longsword": {
        name: "Moon-Touched Longsword",
        identifier: "moon-touched-longsword",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Moon-Touched Rapier": {
        name: "Moon-Touched Rapier",
        identifier: "moon-touched-rapier",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Moon-Touched Scimitar": {
        name: "Moon-Touched Scimitar",
        identifier: "moon-touched-scimitar",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Moon-Touched Shortsword": {
        name: "Moon-Touched Shortsword",
        identifier: "moon-touched-shortsword",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Natural Armor": {
        name: "Natural Armor",
        identifier: "natural-armor",
        type: "Race Feature",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Negative Energy Flood": {
        name: "Negative Energy Flood",
        identifier: "negative-energy-flood",
        type: "Spell",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Oathbow: {
        name: "Oathbow",
        identifier: "oathbow",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Christopher"],
      },
      "Planar Warrior": {
        name: "Planar Warrior",
        identifier: "planar-warrior",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Poison, Basic (vial)": {
        name: "Poison, Basic (vial)",
        identifier: "poison-basic-vial",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      Poisoner: {
        name: "Poisoner",
        identifier: "poisoner",
        type: "Feat",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Potent Poison": {
        name: "Potent Poison",
        identifier: "potent-poison",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Produce Flame": {
        name: "Produce Flame",
        identifier: "produce-flame",
        type: "Spell",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Psionic Power": {
        name: "Psionic Power",
        identifier: "psionic-power",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Psionic Power: Protective Field": {
        name: "Psionic Power: Protective Field",
        identifier: "psionic-power-protective-field",
        type: "Class Feature",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      "Purple Worm Poison": {
        name: "Purple Worm Poison",
        identifier: "purple-worm-poison",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Recall Monster Lore": {
        name: "Recall Monster Lore",
        identifier: "recall-monster-lore",
        type: "Generic Action",
        version: "2.0.0",
        authors: ["Elwin", "Fridan99"],
      },
      "Ring of Evasion": {
        name: "Ring of Evasion",
        identifier: "ring-of-evasion",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Sentinel at Death's Door": {
        name: "Sentinel at Death's Door",
        identifier: "sentinel-at-deaths-door",
        type: "Class Feature",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      "Serpent Venom": {
        name: "Serpent Venom",
        identifier: "serpent-venom",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      Sharpshooter: {
        name: "Sharpshooter",
        identifier: "sharpshooter",
        type: "Feat",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Shell Defense": {
        name: "Shell Defense",
        identifier: "shell-defense",
        type: "Race Feature",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Shield of Missile Attraction": {
        name: "Shield of Missile Attraction",
        identifier: "shield-of-missile-attraction",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin", "Ris"],
      },
      "Sorrowful Fate": {
        name: "Sorrowful Fate",
        identifier: "sorrowful-fate",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Spiny Shield": {
        name: "Spiny Shield",
        identifier: "spiny-shield",
        type: "Spell",
        version: "2.0.0",
        authors: ["tb"],
      },
      "Spirit Shield": {
        name: "Spirit Shield",
        identifier: "spirit-shield",
        type: "Class Feature",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      "Steady Aim": {
        name: "Steady Aim",
        identifier: "steady-aim",
        type: "Class Feature",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Sun Blade": {
        name: "Sun Blade",
        identifier: "sun-blade",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Tasha's Mind Whip": {
        name: "Tasha's Mind Whip",
        identifier: "tashas-mind-whip",
        type: "Spell",
        version: "3.0.0",
        authors: ["Elwin", "Moto Moto"],
      },
      "Telekinetic Adept": {
        name: "Telekinetic Adept",
        identifier: "telekinetic-adept",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Telekinetic Master": {
        name: "Telekinetic Master",
        identifier: "telekinetic-master",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Tipsy Sway": {
        name: "Tipsy Sway",
        identifier: "tipsy-sway",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Tomb of Levistus": {
        name: "Tomb of Levistus",
        identifier: "tomb-of-levistus",
        aliases: ["Eldritch Invocations: Tomb of Levistus"],
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin", "pospa4"],
      },
      "Unwavering Mark": {
        name: "Unwavering Mark",
        identifier: "unwavering-mark",
        type: "Class Feature",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Vengeful Ancestors": {
        name: "Vengeful Ancestors",
        identifier: "vengeful-ancestors",
        type: "Class Feature",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Vigilant Guardian": {
        name: "Vigilant Guardian",
        identifier: "vigilant-guardian",
        type: "Race Feature",
        version: "5.0.0",
        authors: ["Elwin"],
      },
      "Visage of the Astral Self": {
        name: "Visage of the Astral Self",
        identifier: "visage-of-the-astral-self",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Warding Flare": {
        name: "Warding Flare",
        identifier: "warding-flare",
        type: "Class Feature",
        version: "4.0.0",
        authors: ["Elwin"],
      },
      "Warding Maneuver": {
        name: "Warding Maneuver",
        identifier: "warding-maneuver",
        type: "Class Feature",
        version: "3.0.0",
        authors: ["Elwin"],
      },
      "Wyvern Poison": {
        name: "Wyvern Poison",
        identifier: "wyvern-poison",
        type: "Item",
        version: "3.0.0",
        authors: ["Elwin"],
      },
    },
    modern: {
      "Adventurer's Ring": {
        name: "Adventurer's Ring",
        identifier: "adventurers-ring",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Alchemist's Fire": {
        name: "Alchemist's Fire",
        identifier: "alchemists-fire",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Arrow-Catching Shield": {
        name: "Arrow-Catching Shield",
        identifier: "arrow-catching-shield",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Cap of Vanishing": {
        name: "Cap of Vanishing",
        identifier: "cap-of-vanishing",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Cloak of Billowing (Stranger Things)": {
        name: "Cloak of Billowing (Stranger Things)",
        identifier: "cloak-of-billowing-stranger-things",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Clockwork Amulet": {
        name: "Clockwork Amulet",
        identifier: "clockwork-amulet",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin", "thatlonelybugbear"],
      },
      "Channel Divinity": {
        name: "Channel Divinity",
        identifier: "channel-divinity",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Channel Divinity: Vow of Enmity": {
        name: "Channel Divinity: Vow of Enmity",
        identifier: "channel-divinity-vow-of-enmity",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Charger: {
        name: "Charger",
        identifier: "charger",
        type: "Feat",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Dagger of Venom": {
        name: "Dagger of Venom",
        identifier: "dagger-of-venom",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Deathdance: {
        name: "Deathdance",
        identifier: "deathdance",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Defensive Tactics": {
        name: "Defensive Tactics",
        identifier: "defensive-tactics",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Deflect Attacks": {
        name: "Deflect Attacks",
        identifier: "deflect-attacks",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Dread Helm (Stranger Things)": {
        name: "Dread Helm (Stranger Things)",
        identifier: "dread-helm-stranger-things",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Eversmoking Bottle": {
        name: "Eversmoking Bottle",
        identifier: "eversmoking-bottle",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Flame Tongue": {
        name: "Flame Tongue",
        identifier: "flame-tongue",
        type: "Item",
        factory: true,
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Gloves of Missile Snaring": {
        name: "Gloves of Missile Snaring",
        identifier: "gloves-of-missile-snaring",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Goodberry: {
        name: "Goodberry",
        identifier: "goodberry",
        type: "Spell",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Great Weapon Fighting": {
        name: "Great Weapon Fighting",
        identifier: "great-weapon-fighting",
        type: "Feat",
        version: "2.0.0",
        authors: ["Elwin", "WurstKorn"],
      },
      "Great Weapon Master": {
        name: "Great Weapon Master",
        identifier: "great-weapon-master",
        type: "Feat",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Hunter's Lore": {
        name: "Hunter's Lore",
        identifier: "hunters-lore",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Hunter's Prey": {
        name: "Hunter's Prey",
        identifier: "hunters-prey",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Innate Sorcery": {
        name: "Innate Sorcery",
        identifier: "innate-sorcery",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Improved Warding Flare": {
        name: "Improved Warding Flare",
        identifier: "improved-warding-flare",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Lolth’s Sting": {
        name: "Lolth’s Sting",
        identifier: "lolths-sting",
        aliases: ["Lolth's Sting"],
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Oathbow: {
        name: "Oathbow",
        identifier: "oathbow",
        type: "Item",
        factory: true,
        version: "3.0.0",
        authors: ["Elwin", "Christopher"],
      },
      "Oil of Etherealness": {
        name: "Oil of Etherealness",
        identifier: "oil-of-etherealness",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Poison, Basic": {
        name: "Poison, Basic",
        identifier: "poison-basic",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Poisoner: {
        name: "Poisoner",
        identifier: "poisoner",
        type: "Feat",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Potent Poison": {
        name: "Potent Poison",
        identifier: "potent-poison",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Potion of Heroism": {
        name: "Potion of Heroism",
        identifier: "potion-of-heroism",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Potion of Pugilism": {
        name: "Potion of Pugilism",
        identifier: "potion-of-pugilism",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Produce Flame": {
        name: "Produce Flame",
        identifier: "produce-flame",
        type: "Spell",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Purple Worm Poison": {
        name: "Purple Worm Poison",
        identifier: "purple-worm-poison",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Ring of Evasion": {
        name: "Ring of Evasion",
        identifier: "ring-of-evasion",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Rod of the Pact Keeper, +1": {
        name: "Rod of the Pact Keeper, +1",
        identifier: "rod-of-the-pact-keeper-1",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Scimitar of Wounding": {
        name: "Scimitar of Wounding",
        identifier: "scimitar-of-wounding",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Serpent Venom": {
        name: "Serpent Venom",
        identifier: "serpent-venom",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      Sharpshooter: {
        name: "Sharpshooter",
        identifier: "sharpshooter",
        type: "Feat",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Shield of Missile Attraction": {
        name: "Shield of Missile Attraction",
        identifier: "shield-of-missile-attraction",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin", "Ris"],
      },
      "Smoke Grenade": {
        name: "Smoke Grenade",
        identifier: "smoke-grenade",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Spiked Shield": {
        name: "Spiked Shield",
        identifier: "spiked-shield",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Steady Aim": {
        name: "Steady Aim",
        identifier: "steady-aim",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Sun Blade": {
        name: "Sun Blade",
        identifier: "sun-blade",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Superior Hunter's Defense": {
        name: "Superior Hunter's Defense",
        identifier: "superior-hunters-defense",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Superior Hunter's Prey": {
        name: "Superior Hunter's Prey",
        identifier: "superior-hunters-prey",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Sword of Wounding": {
        name: "Sword of Wounding",
        identifier: "sword-of-wounding",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      Ulcrun: {
        name: "Ulcrun",
        identifier: "ulcrun",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Wand of Paralysis": {
        name: "Wand of Paralysis",
        identifier: "wand-of-paralysis",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Warding Flare": {
        name: "Warding Flare",
        identifier: "warding-flare",
        type: "Class Feature",
        version: "2.0.0",
        authors: ["Elwin"],
      },
      "Wraps of Unarmed Power, +1": {
        name: "Wraps of Unarmed Power, +1",
        identifier: "wraps-of-unarmed-power-1",
        type: "Item",
        version: "2.0.0",
        authors: ["Moto Moto"],
      },
      "Wyvern Poison": {
        name: "Wyvern Poison",
        identifier: "wyvern-poison",
        type: "Item",
        version: "2.0.0",
        authors: ["Elwin"],
      },
    },
  },
  monsterAutomations: {
    legacy: {
      "Goblin Psi Commander": {
        identifier: "goblin-psi-commander",
        "Psionic Shield": {
          name: "Psionic Shield",
          identifier: "psionic-shield",
          monsterIdentifier: "goblin-psi-commander",
          type: "feat",
          version: "3.0.0",
          authors: ["Elwin"],
        },
      },
      Lich: {
        identifier: "lich",
        "Negative Energy Tether": {
          name: "Negative Energy Tether",
          identifier: "negative-energy-tether",
          monsterIdentifier: "lich",
          type: "feat",
          version: "3.0.0",
          authors: ["Elwin"],
        },
      },
      Medusa: {
        identifier: "medusa",
        "Petrifying Gaze": {
          name: "Petrifying Gaze",
          identifier: "petrifying-gaze",
          monsterIdentifier: "medusa",
          type: "feat",
          version: "2.0.0",
          authors: ["Elwin", "Moto Moto"],
        },
      },
      Rakshasa: {
        identifier: "rakshasa",
        "Limited Magic Immunity": {
          name: "Limited Magic Immunity",
          identifier: "limited-magic-immunity",
          monsterIdentifier: "rakshasa",
          type: "feat",
          version: "2.0.0",
          authors: ["thatlonelybugbear", "Elwin"],
        },
      },
      "Star Spawn Seer": {
        identifier: "star-spawn-seer",
        "Bend Space": {
          name: "Bend Space",
          identifier: "bend-space",
          monsterIdentifier: "star-spawn-seer",
          type: "feat",
          version: "2.0.0",
          authors: ["Elwin"],
        },
      },
    },
    modern: {
      Medusa: {
        identifier: "medusa",
        "Petrifying Gaze": {
          name: "Petrifying Gaze",
          identifier: "petrifying-gaze",
          monsterIdentifier: "medusa",
          type: "feat",
          version: "2.0.0",
          authors: ["Elwin"],
        },
      },
      "Goblin Boss": {
        identifier: "goblin-boss",
        "Redirect Attack": {
          name: "Redirect Attack",
          identifier: "redirect-attack",
          monsterIdentifier: "goblin-boss",
          type: "feat",
          version: "2.0.0",
          authors: ["TMinz"],
        },
      },
    },
  },
};

export function setConfig() {
  foundry.utils.setProperty(CONFIG, moduleName, automationConfig);
}
